/* 04-protocol.h - Game Protocol Message Definitions
 *
 * Defines the message types and structures for client-server communication.
 * Supports both WebSocket (web clients) and SSH (terminal clients) transports.
 * Uses JSON for message serialization with cJSON library.
 *
 * Protocol flow:
 *   1. Client connects and sends MSG_JOIN with player name
 *   2. Server responds with MSG_GAMESTATE
 *   3. Client sends MSG_ACTION or MSG_END_TURN during their turn
 *   4. Server broadcasts updated MSG_GAMESTATE to all players
 *   5. Server may send MSG_NARRATIVE for game events
 *   6. On error, server sends MSG_ERROR
 */

#ifndef SYMBELINE_PROTOCOL_H
#define SYMBELINE_PROTOCOL_H

#include "../../libs/cJSON.h"
#include "../core/05-game.h"
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

/* ========================================================================== */
/*                              Message Types                                 */
/* ========================================================================== */

/* {{{ MessageType enum
 * All message types for client-server communication.
 * Client→Server messages are handled by server handlers.
 * Server→Client messages are generated by server functions.
 */
typedef enum {
    /* Client → Server messages */
    MSG_JOIN,               /* Player joining game */
    MSG_LEAVE,              /* Player leaving game */
    MSG_ACTION,             /* Game action (play, buy, attack, etc.) */
    MSG_DRAW_ORDER,         /* Response to draw order request */
    MSG_CHAT,               /* Chat message to other players */
    MSG_END_TURN,           /* End current turn */

    /* Server → Client messages */
    MSG_GAMESTATE,          /* Full game state update */
    MSG_NARRATIVE,          /* Narrative text from DM */
    MSG_ERROR,              /* Error response */
    MSG_PLAYER_JOINED,      /* Notification: player joined */
    MSG_PLAYER_LEFT,        /* Notification: player left */
    MSG_DRAW_ORDER_REQUEST, /* Request draw order from player */
    MSG_CHOICE_REQUEST,     /* Request a choice (scrap, discard, etc.) */
    MSG_GAME_OVER,          /* Game has ended */

    MSG_TYPE_COUNT          /* Sentinel for array sizing */
} MessageType;
/* }}} */

/* {{{ ProtocolError enum
 * Error codes for protocol validation and game state errors.
 */
typedef enum {
    PROTOCOL_OK = 0,

    /* Parse/format errors */
    PROTOCOL_ERROR_MALFORMED_JSON,
    PROTOCOL_ERROR_MISSING_TYPE,
    PROTOCOL_ERROR_UNKNOWN_TYPE,
    PROTOCOL_ERROR_MISSING_FIELD,
    PROTOCOL_ERROR_INVALID_FIELD_TYPE,
    PROTOCOL_ERROR_INVALID_VALUE,

    /* Game state errors */
    PROTOCOL_ERROR_NOT_YOUR_TURN,
    PROTOCOL_ERROR_INVALID_PHASE,
    PROTOCOL_ERROR_GAME_NOT_STARTED,
    PROTOCOL_ERROR_GAME_ALREADY_STARTED,
    PROTOCOL_ERROR_GAME_FULL,
    PROTOCOL_ERROR_NOT_IN_GAME,

    /* Action errors */
    PROTOCOL_ERROR_INVALID_ACTION,
    PROTOCOL_ERROR_CARD_NOT_FOUND,
    PROTOCOL_ERROR_CARD_NOT_IN_HAND,
    PROTOCOL_ERROR_INSUFFICIENT_TRADE,
    PROTOCOL_ERROR_INSUFFICIENT_COMBAT,
    PROTOCOL_ERROR_INVALID_TARGET,
    PROTOCOL_ERROR_INVALID_SLOT,
    PROTOCOL_ERROR_INVALID_DRAW_ORDER,

    PROTOCOL_ERROR_COUNT    /* Sentinel */
} ProtocolError;
/* }}} */

/* {{{ ChoiceType enum
 * Types of choices the server can request from a player.
 */
typedef enum {
    CHOICE_DRAW_ORDER,      /* Select order to draw cards */
    CHOICE_SCRAP_HAND,      /* Select card from hand to scrap */
    CHOICE_SCRAP_DISCARD,   /* Select card from discard to scrap */
    CHOICE_SCRAP_TRADE_ROW, /* Select card from trade row to scrap */
    CHOICE_DISCARD,         /* Select card to discard */
    CHOICE_ACQUIRE_FREE,    /* Select free card to acquire */
    CHOICE_BASE_PLACEMENT,  /* Choose frontier or interior */

    CHOICE_TYPE_COUNT       /* Sentinel */
} ChoiceType;
/* }}} */

/* ========================================================================== */
/*                              Message Structures                            */
/* ========================================================================== */

/* {{{ Message
 * A protocol message with type, sender, and payload.
 * The payload is a cJSON object containing type-specific data.
 */
typedef struct {
    MessageType type;       /* Message type */
    int player_id;          /* Sender's player ID (-1 for server) */
    cJSON* payload;         /* Message-specific data (owned by message) */
    uint64_t timestamp;     /* Unix timestamp in milliseconds */
} Message;
/* }}} */

/* ========================================================================== */
/*                            Message Lifecycle                               */
/* ========================================================================== */

/* {{{ message_create
 * Creates a new message with the given type.
 * Payload is initialized to empty object.
 * Returns NULL on allocation failure.
 */
Message* message_create(MessageType type);
/* }}} */

/* {{{ message_free
 * Frees a message and its payload.
 * Safe to call with NULL.
 */
void message_free(Message* msg);
/* }}} */

/* ========================================================================== */
/*                            Protocol Parsing                                */
/* ========================================================================== */

/* {{{ protocol_parse
 * Parses a JSON string into a Message.
 * Sets error code on failure.
 * Returns NULL on error, caller must check error.
 * Caller owns returned message.
 */
Message* protocol_parse(const char* json, ProtocolError* error);
/* }}} */

/* {{{ protocol_serialize
 * Serializes a Message to JSON string.
 * Caller must free returned string.
 * Returns NULL on failure.
 */
char* protocol_serialize(Message* msg);
/* }}} */

/* ========================================================================== */
/*                            Type Conversion                                 */
/* ========================================================================== */

/* {{{ message_type_from_string
 * Converts a string (e.g., "join") to MessageType.
 * Returns MSG_TYPE_COUNT if unknown.
 */
MessageType message_type_from_string(const char* str);
/* }}} */

/* {{{ message_type_to_string
 * Converts a MessageType to string (e.g., "join").
 * Returns "unknown" for invalid types.
 */
const char* message_type_to_string(MessageType type);
/* }}} */

/* {{{ protocol_error_to_string
 * Returns human-readable error message.
 */
const char* protocol_error_to_string(ProtocolError error);
/* }}} */

/* {{{ protocol_error_code
 * Returns short error code string for JSON (e.g., "not_your_turn").
 */
const char* protocol_error_code(ProtocolError error);
/* }}} */

/* {{{ choice_type_to_string
 * Converts a ChoiceType to string.
 */
const char* choice_type_to_string(ChoiceType type);
/* }}} */

/* ========================================================================== */
/*                            Validation Helpers                              */
/* ========================================================================== */

/* {{{ protocol_validate_has_field
 * Checks if payload has a field of the expected type.
 * Returns PROTOCOL_OK or appropriate error.
 */
ProtocolError protocol_validate_has_string(cJSON* payload, const char* field);
ProtocolError protocol_validate_has_number(cJSON* payload, const char* field);
ProtocolError protocol_validate_has_array(cJSON* payload, const char* field);
ProtocolError protocol_validate_has_object(cJSON* payload, const char* field);
/* }}} */

/* {{{ protocol_validate_number_range
 * Validates a number field is within [min, max].
 * Returns PROTOCOL_OK or PROTOCOL_ERROR_INVALID_VALUE.
 */
ProtocolError protocol_validate_number_range(cJSON* payload, const char* field,
                                             int min, int max);
/* }}} */

/* ========================================================================== */
/*                         Server Message Generation                          */
/* ========================================================================== */

/* {{{ protocol_create_gamestate
 * Creates a MSG_GAMESTATE message with serialized game state.
 * Filters state for the specified player (hides opponent hands).
 * Returns NULL on failure.
 */
Message* protocol_create_gamestate(Game* game, int player_id);
/* }}} */

/* {{{ protocol_create_narrative
 * Creates a MSG_NARRATIVE message with text.
 */
Message* protocol_create_narrative(const char* text);
/* }}} */

/* {{{ protocol_create_error
 * Creates a MSG_ERROR message with code and description.
 */
Message* protocol_create_error(ProtocolError error, const char* details);
/* }}} */

/* {{{ protocol_create_player_joined
 * Creates a MSG_PLAYER_JOINED notification.
 */
Message* protocol_create_player_joined(int player_id, const char* name);
/* }}} */

/* {{{ protocol_create_player_left
 * Creates a MSG_PLAYER_LEFT notification.
 */
Message* protocol_create_player_left(int player_id);
/* }}} */

/* {{{ protocol_create_draw_order_request
 * Creates a MSG_DRAW_ORDER_REQUEST for the given card count.
 */
Message* protocol_create_draw_order_request(int card_count);
/* }}} */

/* {{{ protocol_create_choice_request
 * Creates a MSG_CHOICE_REQUEST for the given choice type.
 * Options array contains valid choices.
 */
Message* protocol_create_choice_request(ChoiceType type, cJSON* options);
/* }}} */

/* {{{ protocol_create_game_over
 * Creates a MSG_GAME_OVER message with winner info.
 */
Message* protocol_create_game_over(int winner_id, const char* reason);
/* }}} */

/* ========================================================================== */
/*                         Client Message Handling                            */
/* ========================================================================== */

/* {{{ Handler function type
 * Function pointer for message handlers.
 * game: Current game state (may be NULL for join)
 * player_id: ID of sending player (-1 if not yet joined)
 * msg: The message to handle
 * Returns error code (PROTOCOL_OK on success)
 */
typedef ProtocolError (*MessageHandler)(Game* game, int player_id,
                                        Message* msg, void* context);
/* }}} */

/* {{{ protocol_get_handler
 * Returns the handler for a client message type.
 * Returns NULL for server→client message types.
 */
MessageHandler protocol_get_handler(MessageType type);
/* }}} */

/* {{{ protocol_dispatch
 * Dispatches a message to its handler.
 * Returns error code from handler or PROTOCOL_ERROR_UNKNOWN_TYPE.
 */
ProtocolError protocol_dispatch(Game* game, int player_id,
                               Message* msg, void* context);
/* }}} */

/* ========================================================================== */
/*                         JSON Schema Documentation                          */
/* ========================================================================== */

/*
 * Client → Server Messages:
 *
 * MSG_JOIN:
 *   {"type": "join", "name": "PlayerName"}
 *
 * MSG_LEAVE:
 *   {"type": "leave"}
 *
 * MSG_ACTION (play card):
 *   {"type": "action", "action": "play_card", "card_id": "instance_id_here"}
 *
 * MSG_ACTION (buy card):
 *   {"type": "action", "action": "buy_card", "slot": 0-4}
 *
 * MSG_ACTION (buy explorer):
 *   {"type": "action", "action": "buy_explorer"}
 *
 * MSG_ACTION (attack player):
 *   {"type": "action", "action": "attack_player", "target": 1, "amount": 5}
 *
 * MSG_ACTION (attack base):
 *   {"type": "action", "action": "attack_base", "target": 1, "base_id": "id", "amount": 3}
 *
 * MSG_ACTION (scrap):
 *   {"type": "action", "action": "scrap_hand", "card_id": "instance_id"}
 *   {"type": "action", "action": "scrap_discard", "card_id": "instance_id"}
 *   {"type": "action", "action": "scrap_trade_row", "slot": 2}
 *
 * MSG_DRAW_ORDER:
 *   {"type": "draw_order", "order": [3, 1, 0, 2, 4]}
 *
 * MSG_END_TURN:
 *   {"type": "end_turn"}
 *
 * MSG_CHAT:
 *   {"type": "chat", "message": "Hello!"}
 *
 *
 * Server → Client Messages:
 *
 * MSG_GAMESTATE:
 *   {"type": "gamestate", "turn": 12, "phase": "main", "you": {...}, ...}
 *
 * MSG_NARRATIVE:
 *   {"type": "narrative", "text": "The dire bear charges..."}
 *
 * MSG_ERROR:
 *   {"type": "error", "code": "not_your_turn", "message": "It's not your turn"}
 *
 * MSG_PLAYER_JOINED:
 *   {"type": "player_joined", "player_id": 1, "name": "Alice"}
 *
 * MSG_PLAYER_LEFT:
 *   {"type": "player_left", "player_id": 1}
 *
 * MSG_DRAW_ORDER_REQUEST:
 *   {"type": "draw_order_request", "count": 5}
 *
 * MSG_CHOICE_REQUEST:
 *   {"type": "choice_request", "choice_type": "scrap_hand", "options": [...]}
 *
 * MSG_GAME_OVER:
 *   {"type": "game_over", "winner_id": 0, "reason": "Player 2 has no authority"}
 */

#endif /* SYMBELINE_PROTOCOL_H */
